# Create a namespace "Ecommerce"  
apiVersion: v1 
kind: Namespace 
metadata: 
    name: ecommerce 
    labels: 
        name: ecommerce 
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: azuredisk-db-pvc 
  namespace: ecommerce
  labels:
    app: webapp
    env: develop 
spec: 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: managed-csi 
  resources: 
    requests: 
      storage: 1Gi     


--- 
# Create a hrweb deployment which uses a web server and above persistent volume 
kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: shoppingkart 
  namespace: ecommerce 
spec: 
  selector: 
    matchLabels: 
      app: webapp 
    matchExpressions: 
      - {key: env, operator: In, values: ["develop"]} 
  replicas: 1   
  template: 
    metadata:  
      labels: 
        app: webapp 
        env: develop 
    spec: 
      containers: 
      - name: webcontainer 
        image: nginx:1.14.2 
        ports: 
        - containerPort: 80 
        volumeMounts: 
        - name: azure 
          mountPath: /usr/share/nginx/html 
      volumes: 
      - name: azure 
        persistentVolumeClaim: 
         claimName: azuredisk-db-pvc 



